// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://jzcuynhsffjlgtzfwvnb.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Imp6Y3V5bmhzZmZqbGd0emZ3dm5iIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDk5MDM4NTksImV4cCI6MjA2NTQ3OTg1OX0.1pwXNOA8VWoCUVvGySdatAkzl4Hhv3cmxdAE3mN8fFk";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);